### ISSUE TITLE
Fix sidebar

### ISSUE THREAD

**Issue by NadjibSb** [Hackuarium/bioreactor-ui#10]
- Change position to fixed
- When back button is clicked, the focused navbar element doesn't change
- Prevent content to overflow horizontally (apply max-with)

**Comment by HammacheAbir** [comment]
@NadjibSb The fixed position of the menu can only be applied on menus displayed on the top of the website. However I suggest to add the possibility of choosing the menu's mode (static or overflow) so that it doesn't take much space on the page.

**Comment by NadjibSb** [comment]
> @NadjibSb The fixed position of the menu can only be applied on menus displayed on the top of the website. However I suggest to add the possibility of choosing the menu's mode (static or overflow) so that it doesn't take much space on the page.

We'll plan that for future enhancement, for now the priority is for the targeted screens.
