### ISSUE TITLE
Display tip about a specific field

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/bioreactor-ui#20]
Where did you find the units for the first parameters ? Because it is the log of a ratio there is no units. 

![image](https://user-images.githubusercontent.com/1484241/123502771-20717900-d64f-11eb-835e-cb079909ea9d.png)

**Comment by lpatiny** [comment]
There is a mistake in legoino-device-information and I will fix it.

**Comment by NadjibSb** [comment]
I get the units dynamically from the informations I receive from the device

<img width="519" alt="Screen Shot 2021-06-26 at 10 22 04 PM" src="https://user-images.githubusercontent.com/25468825/123526015-f8285f80-d6cc-11eb-89eb-c8165a83741c.png">

**Comment by lpatiny** [comment]
Yes and even for me it was not obvious what was this unit ...

Please could you add in each box a small question mark (on the top right of the box). 

![image](https://user-images.githubusercontent.com/1484241/123532862-39426300-d711-11eb-928e-2b58936819e7.png)

And with mouse over show the 'description'. This question mark should only be present if the `description` field is defined.
