### ISSUE TITLE
Create 'advanced' mode

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/bioreactor-ui#21]
We should be able to interact with the device like we would no in a terminal.

There would be one button for 'help' (sending 'h'), one button for 'settings' (sending 's') and the the possibility to input whatever and send it. The result would appear maybe in a terminal like window (green fixed width characters on black background). But you did a good job for design so you may do whatever you think is better.

![image](https://user-images.githubusercontent.com/1484241/123502820-721a0380-d64f-11eb-8293-f3b21573bda9.png)

**Comment by NadjibSb** [comment]
closed by 7279796602a6865ab072c820278a25b156c3ac35 & 40416c26aaf5fac19e19bc2e485b4a5b709671fd & 070c49f66dac8071f14d337c6fcd740dabff6814
