### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/bioreactor-ui#22]
For the configuration I would skip the 'Save' button and save on loose focus of the input field.

I would also add a small 'saved' information that appears couple of seconds in the bottom to show the user that it is actually saved. Another way would be to have a green box around the input field when data is saved and the short time when it is saving it is red and goes back to green once it is saved. 

Maybe there is also better UI as well.

![image](https://user-images.githubusercontent.com/1484241/123502885-ccb35f80-d64f-11eb-929c-5af674c3697c.png)

**Comment by NadjibSb** [comment]
closed by 9fd0b20ca91c910cfefbd0c8ccdbd89c5d5d4f8b

**Comment by NadjibSb** [comment]
closed by 9fd0b20ca91c910cfefbd0c8ccdbd89c5d5d4f8b
