### ISSUE TITLE
Automatic detection of device kind ?

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/bioreactor-ui#24]
I added a new method that allows from 'device-util' to retrieve device info from the deviceID `DevicesInfo.fromDeviceID(id)`. 

Each instrument has an ID that we use to store the log and retrieve information about the device. It is a 2 bytes code and the first byte is related to the kind of device it is. This means that from this code we can select automatically the corresponding device. 

https://github.com/Hackuarium/legoino-device-information/blob/master/src/index.js#L19

1. Please add in the 'Select device' drop down menu in parenthesis what kind of device it is (if available).

![image](https://user-images.githubusercontent.com/1484241/123533087-e5d11480-d712-11eb-8260-19d32903d484.png)

2. When you select a device from the drop down menu please change automatically the `Device type` if defined.

**Comment by NadjibSb** [comment]
closed by 3eb8e8fd3d675a6ffd4951fc5f498cd1d0bb0f51
