### ISSUE TITLE
Local devices: give the possibility to give a unique short name

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/bioreactor-ui#28]
For each local device we should be able to assign a short name. This is the name that will be presented in the menu.

The list of ever connected devices stays (even if it is not connected) and we could display the status of the devices. In order to test for another device you can use the instruction `uq21570`. By default the device ID is 21570 but you can enter `uq21571` for example to change the ID and have a new device.

![image](https://user-images.githubusercontent.com/1484241/123549010-7a656200-d767-11eb-9cf9-c9bbb561892c.png)

**Comment by NadjibSb** [comment]
closed by 3c9c0a827aa1a33b6b01bc0cdb4791f290ac6623
