### ISSUE TITLE
Infinite addition of undefined broadcast device

### ISSUE THREAD

**Issue by lpatiny** [Hackuarium/bioreactor-ui#30]
When you try to add the WSS mqtt.hackuarium.org on port 443 Computer device it works. But coming back on the list of broadcast device there is a huge growing list of undefined devices appearing.

![image](https://user-images.githubusercontent.com/1484241/124439457-bb6a0180-dd79-11eb-9a75-78430d37a32b.png)

**Comment by NadjibSb** [comment]
related to #16

**Comment by NadjibSb** [comment]
closed by d43c01c659a2814145179035c0cbecae6aaa02c3
