### ISSUE TITLE
Check negative value in Steps

### ISSUE THREAD

**Issue by andrescvargasr** [Hackuarium/bioreactor-ui#44]
When you set a negative value in the Steps ([example 2](https://docs.hackuarium.org/docs/bioreactor/using/steps#example-2)) the convertion to binary is with '-' not '1' for the first bit:

- BB32808 -> BB-32768 -> '-' '0' '0' '0' ... '1' '0' '1' '0' '0' '0'

**Comment by lpatiny** [comment]
And this is the default value after a reset of the flash (FFFF). I think we also define this value internally as ERROR_VALUE or something like that.

**Comment by andrescvargasr** [comment]
Solve in commit [a06d774](https://github.com/Hackuarium/bioreactor-ui/commit/a06d774ce5f587962e7898ad31aa9278e985a163)
